# Generated by Django 5.0.2 on 2024-03-15 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chathistory_pdf_file_delete_legaldocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='is_user_message',
        ),
    ]
